# Shougoさんのを参考にする
[[plugins]] # Required
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('kaoriya')"
build = 'make'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

#[[plugins]]
#repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

#[[plugins]]
#repo = 'kana/vim-filetype-haskell'
#on_ft = 'haskell'

#[[plugins]]
#repo = 'Shougo/unite-sudo'


#[[plugins]]
#repo = 'pangloss/vim-javascript'
#on_ft = 'javascript'
#hook_add = '''
#let g:javascript_plugin_jsdoc = 1
#let g:javascript_plugin_flow = 1
#'''

#[[plugins]] # jsx syntax highlight & indent
#repo = 'mxw/vim-jsx'
#on_ft = 'javascript'
#hook_add = '''
#let g:jsx_ext_required = 0
#'''

#[[plugins]] # jsx syntax highlight & indent
#repo = 'maxmellon/vim-jsx-pretty'
#depends = ['pangloss/vim-javascript']
#on_ft = 'javascript'
#hook_add = '''
#let g:vim_jsx_pretty_enable_jsx_highlight = 1
#let g:vim_jsx_pretty_colorful_config = 1
#'''


#[[plugins]]
#repo = 'othree/es.next.syntax.vim'
#on_ft = 'javascript'
#[[plugins]]
#repo = 'othree/javascript-libraries-syntax.vim'
#on_ft = 'javascript'

#[[plugins]]
#repo = 'itchyny/vim-haskell-indent'
#on_ft = 'haskell'

#[[plugins]]
#repo = 'udalov/kotlin-vim'
#on_ft = 'kotlin'

#[[plugins]]
#repo = 'shawncplus/phpcomplete.vim'
#on_ft = 'php'

#[[plugins]]
#repo = 'jiangmiao/simple-javascript-indenter'
#on_ft = 'javascript'

#[[plugins]]
#repo = 'thinca/vim-ft-diff_fold'
#on_ft = 'diff'

#[[plugins]]
#repo = 'thinca/vim-ft-vim_fold'
#on_ft = 'vim'

#[[plugins]]
#repo = 'thinca/vim-ft-help_fold'
#on_ft = 'help'

#[[plugins]]
#repo = 'yomi322/vim-gitcomplete'
#on_ft = 'vimshell'

#[[plugins]]
#repo = 'vim-jp/cpp-vim'
#on_ft = 'cpp'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

#[[plugins]]
#repo = 'vim-jp/autofmt'

#[[plugins]]
#repo = 'kana/vim-textobj-user'

#[[plugins]]
#repo = 'hynek/vim-python-pep8-indent'
#on_ft = 'python'

# Operators
#[[plugins]]
#repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

#[[plugins]] # completion
#repo = 'marijnh/tern_for_vim'
#on_ft = 'javascript'
#build = 'npm install'

#[[plugins]]
#repo = 'vim-ruby/vim-ruby'
#on_map = '<Plug>'
#on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'sorah/unite-ghq'
#on_source = 'unite.vim'

#[[plugins]]
#repo = 'osyo-manga/unite-vimpatches'

#[[plugins]]
#repo = 'Shougo/unite-build'

#[[plugins]]
#repo = 'ujihisa/vimshell-ssh'
#on_ft = 'vimshell'

#[[plugins]]
#repo = 'Shougo/unite-help'
#on_source = 'unite.vim'

#[[plugins]]
#repo = 'mattn/webapi-vim'

#[[plugins]]
#repo = 'jelera/vim-javascript-syntax'
#on_ft = 'javascript'

#[[plugins]]
#repo = 'JesseKPhillips/d.vim'
#on_ft = 'd'

#[[plugins]]
#repo = 'nsf/gocode'
#rtp = 'vim'
#on_ft = 'go'

#[[plugins]]
#repo = 'vim-jp/vimdoc-ja'
#on_ft = 'help'

#[[plugins]]
#repo = 'machakann/vim-vimhelplint'
#hook_add = '''
#  autocmd MyAutoCmd FileType
#  \ help nnoremap <silent><buffer> ,r  :<C-u>VimhelpLint!<CR>
#'''

#[[plugins]]
#repo = 'Kocha/vim-unite-tig'

#[[plugins]]
#repo = 'thinca/vim-themis'

#[[plugins]]
#repo = 'cocopon/iceberg.vim'

#[[plugins]]
#repo = 'vim-jp/syntax-vim-ex'

### ADD

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'thinca/vim-singleton'
if = "has('clientserver')"

[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'moll/vim-node'
[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'ap/vim-css-color'
[[plugins]]
repo = 'mustache/vim-mustache-handlebars'
[[plugins]]
repo = 'chase/vim-ansible-yaml'
[[plugins]]
repo = 'nginx.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'itchyny/thumbnail.vim'
[[plugins]]
repo = 'vim-scripts/diffchar.vim'
[[plugins]]
repo = 'chrisbra/BufTimer'
[[plugins]]
repo = 'chrisbra/Recover.vim'
[[plugins]]
repo = 'AndrewRadev/inline_edit.vim'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
[[plugins]]
repo = 'AndrewRadev/sideways.vim'

[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'gregsexton/gitv'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 't9md/vim-quickhl'
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'rhysd/clever-f.vim'


[[plugins]]
repo = 'heavenshell/vim-jsdoc'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins]]
repo = 'mopp/autodirmake.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
if = "has('conceal')"

[[plugins]]
repo = 'neomake/neomake'
